# Generated by Django 6.0.1 on 2026-05-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['pickup_time']},
        ),
        migrations.AlterModelOptions(
            name='rideevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
